name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# needed for GHCR login with GITHUB_TOKEN
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Only build & push on main branch pushes (not PRs)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    env:
      # To override the image name, set these secrets in the repo settings
      GHCR_IMAGE: sharkyrawr/godot-dockerhub
      DOCKERHUB_IMAGE: sophiefox/godot-dockerhub

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set image/tag metadata (lowercase for GHCR)
        id: meta
        shell: bash
        run: |
          echo "ghcr_image=$(echo "$GHCR_IMAGE" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "dockerhub_image=$(echo "$DOCKERHUB_IMAGE" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "tag=latest" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (GHCR + Docker Hub)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.ghcr_image }}:${{ steps.meta.outputs.tag }}
            docker.io/${{ steps.meta.outputs.dockerhub_image }}:${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
