name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# needed for GHCR login with GITHUB_TOKEN
permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    # Only build & push on main branch pushes (not PRs) or manual triggers
    if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'

    strategy:
      matrix:
        edition: ['', '_mono']
        include:
          - edition: ''
            suffix: ''
            edition_name: 'standard'
          - edition: '_mono'
            suffix: '-mono'
            edition_name: 'mono'

    env:
      # To override the image name, set these secrets in the repo settings
      GHCR_IMAGE: ghcr.io/sharkyrawr/godot-docker
      DOCKERHUB_IMAGE: docker.io/sophiefox/godot-docker
      GODOT_VERSION: 4.5.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.GHCR_IMAGE }}
            ${{ env.DOCKERHUB_IMAGE }}
          tags: |
            type=raw,value=latest${{ matrix.suffix }}
            type=raw,value=${{ env.GODOT_VERSION }}${{ matrix.suffix }}
            type=raw,value=${{ env.GODOT_VERSION }}-${{ matrix.edition_name }}
            type=ref,event=branch,suffix=${{ matrix.suffix }}
            type=ref,event=pr,suffix=${{ matrix.suffix }}
            type=sha,suffix=${{ matrix.suffix }}
          flavor: |
            latest=false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (GHCR + Docker Hub)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.edition_name }}
          cache-to: type=gha,mode=max,scope=${{ matrix.edition_name }}
          provenance: mode=max
          sbom: true
          build-args: |
            EDITION=${{ matrix.edition }}
            VERSION=${{ env.GODOT_VERSION }}

      - uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.GHCR_IMAGE }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
